version: 2

sources:
  - name: raw
    database: sentinel-platform-492311
    schema: sentinel_raw

    tables:
      - name: raw_users
      - name: raw_user_profile
      - name: raw_transactions
      - name: raw_events

models:
  - name: stg_users
    description: "Staging users table"
    columns:
      - name: user_id
        tests:
          - not_null
          # - unique   # optional

  - name: stg_transactions
    description: "Transactions staging"
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique

  - name: stg_events
    description: "User events"

    columns:
      - name: user_id
        tests:
          - not_null

      - name: event_timestamp
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_id
            - event_timestamp